### ISSUE TITLE
服务端控制台问题

### ISSUE THREAD

**Issue by nanvon** [a1098832322/MarketServer#1]
打开“添加商品信息 展示商品列表 商品类型列表 查看用户购物车 查看用户已购买”这几个连接都打不开了

**Comment by a1098832322** [comment]
好像是挂在云服务器上的服务挂掉了，我等等去看看------------------ 原始邮件 ------------------
发件人: "南枫"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 下午5:29
收件人: "a1098832322/MarketServer"<MarketServer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [a1098832322/MarketServer] 服务端控制台问题 (#1)



打开“添加商品信息 展示商品列表 商品类型列表 查看用户购物车 查看用户已购买”这几个连接都打不开了
 
&mdash;

**Comment by a1098832322** [comment]
已修复，刚上去看了一下，这段时间没管，发现是数据库被勒索病毒加密了-_-！
现在已经数据库回滚修复，不过你的账号可能要重新注册一下才能实现正常的：购买历史、购物车、购买商品等功能

**Comment by nanvon** [comment]
还是不行，显示这个：
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Nov 01 18:06:05 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by a1098832322** [comment]
噢噢，你访问的这个是后端接口，是数据传输用的，并没有实际的页面


发自我的iPhone
