### ISSUE TITLE
请问服务器部署的步骤

### ISSUE THREAD

**Issue by tqnwhz** [a1098832322/MarketServer#2]
您好!
我想请问下您关于服务器部署的一些细节,我之前没有接触过服务器这方面的东西,
问了很多人才勉强编译出target 的jar包,但运行jar包后也不能访问对应端口,控制台也会报这种错误.
![image](https://user-images.githubusercontent.com/39870399/71542567-e44e5100-29a2-11ea-80d9-bf207bb14c2f.png)
因此想请问一下您是否方便详细介绍一下服务器部署的步骤,在此表示无比的感谢!

**Comment by a1098832322** [comment]
是这样的，商城服务端是没有做页面的，只有接口。你可以访问：
http://ip:port/swagger-ui.html
这个地址来查看并调试所有接口

**Comment by a1098832322** [comment]
> 您好!
> 我想请问下您关于服务器部署的一些细节,我之前没有接触过服务器这方面的东西,
> 问了很多人才勉强编译出target 的jar包,但运行jar包后也不能访问对应端口,控制台也会报这种错误.
> ![image](https://user-images.githubusercontent.com/39870399/71542567-e44e5100-29a2-11ea-80d9-bf207bb14c2f.png)
> 因此想请问一下您是否方便详细介绍一下服务器部署的步骤,在此表示无比的感谢!

![image](https://user-images.githubusercontent.com/17981612/71543190-a1dd4200-29ab-11ea-99f3-c9cded0c6148.png)
是这样的一个界面，我已经用Swagger把所有的接口进行了统一展现

**Comment by tqnwhz** [comment]
非常感谢您的回复!
我大致明白一些了,祝您生活美满~
