### ISSUE TITLE
私有依赖上传问题

### ISSUE THREAD

**Issue by Yy-ss7** [a1098832322/MarketServer#6]
您好  请教一下怎么打包哪个私有依赖呀  就差这一步了

**Comment by a1098832322** [comment]
> 您好 请教一下怎么打包哪个私有依赖呀 就差这一步了

私有依赖文件夹里面有一个txt
你先安装好maven环境，然后cd到“私有依赖”这个文件夹下面，把txt里面的maven指令复制粘贴到控制台里面执行就可以了

**Comment by Yy-ss7** [comment]
已经跑起来了 感谢
